### ISSUE TITLE
demo page not running

### ISSUE THREAD

**Issue by jhades** [FuelInteractive/fuel-ui#1]
Cool project. I tried to run the examples: npm install went fine, gulp (default) run OK, but while loading the index.html page I go this:

```
Failed to load resource: the server responded with a status of 404 (Not Found)
config.js:1 Uncaught ReferenceError: System is not defined
localhost/:9 Uncaught ReferenceError: System is not defined
```

For info I'm using:

```
node 4.1.2
npm 3.3.6
```

**Comment by coryshaw1** [comment]
What browser are you using?

**Comment by StacyGay** [comment]
Run jspm install, sorry need to make that part of the npm install. And if that's not the case, like @coryshaw1 was getting at, we were having trouble getting this version of system.js to run on Firefox

**Comment by jhades** [comment]
The demo works well on Chrome. Submitted a PR to fix the build: https://github.com/FuelInteractive/fuel-ui/pull/2

**Comment by jhades** [comment]
note to anyone running the examples and getting a blank page: it takes around maybe 10 seconds for everything to load while jspm grabs everything from the server

**Comment by jhades** [comment]
closed by https://github.com/FuelInteractive/fuel-ui/pull/2
