### ISSUE TITLE
Setting initial value of DateRangePicker

### ISSUE THREAD

**Issue by bbrink68** [FuelInteractive/fuel-ui#40]
Hey again,

Any idea how I can set the initial value of the start and end dates of a DateRangePicker instance?  I tried using the `[value]="dateRange"` attribute and setting `dateRange = new DateRange(new Date(), new Date())` but it does not see to want to display the values in the inputs.

I also seen some more `Inputs()` on `DateRangePicker.ts` called `inputEndDate` & `inputStartDate` but neither of those were working either.  Is this possible?

**Comment by StacyGay** [comment]
Yep, I see the problem.  The inputs weren't getting updated correctly based on the start and end values.  Two-way binding should be working correctly now on value(dateRange), startDate and endDate.

I've updated the demo and readme to reflect the correct bindings.

These changes should be reflected in the npm package version 0.1.4.

Thanks for the heads up!
