### ISSUE TITLE
Carousel animations not working on firefox

### ISSUE THREAD

**Issue by StacyGay** [FuelInteractive/fuel-ui#60]
Animations are pushing the next frame out of view on firefox. 

May want to look into another approach to support swiping on mobile

**Comment by coryshaw1** [comment]
Seems to not work on Windows Firefox (tested v46.0.1). This works correctly on Firefox Developer Edition v48.0a2 on OSX.

I do agree that the animations should be handled differently. May want to look into using the AnimationBuilder, similar to the Collapse directive's implementation. If we want to work more with gestures, we may need to look elsewhere.

**Comment by StacyGay** [comment]
New version of carousel is working on IE and FF.
Animations do not work on IE or FF < v48 as a quirk of the current version of animation builder.
Changes included as of https://github.com/FuelInteractive/fuel-ui/releases/tag/0.3.1
