### ISSUE TITLE
Listing Fuel UI on angular.io

### ISSUE THREAD

**Issue by mmrath** [FuelInteractive/fuel-ui#64]
Hi

This is not an issue.
You are doing a great job.
Fuel UI is a nice component library which I think should be listed at [https://angular.io/resources/](url). 
I think you will need to fill the form at [https://docs.google.com/a/rangle.io/forms/d/1qzWaDpTgTPe4iPDRF_VCT9aHXKimUocwlFnVJUdKabY/viewform?c=0&w=1](url)

Thanks

**Comment by coryshaw1** [comment]
Thank you for the kind words! I appreciate you sending the link, and we have submitted a request to be added as a listing to the resources page. Will keep this issue open until we hear back from the Angular team.

**Comment by coryshaw1** [comment]
We've officially been listed on https://angular.io/resources/!

Closing this issue now.
