### ISSUE TITLE
Documentation: How to use with angular-cli

### ISSUE THREAD

**Issue by mmrath** [FuelInteractive/fuel-ui#65]
It would be nice if there is some documentation around how to use the library with angular-cli

**Comment by Joebob12** [comment]
Hey @mmrath any luck on this? Trying to get this working also.

**Comment by coryshaw1** [comment]
Sorry for the late response, got around to looking into this.

To get it working please follow these steps:

   1.)  `npm install fuel-ui font-awesome bootstrap@^4.0.0-alpha.2 --save`
   2.)  Go to your `angular-cli-build.js` file, and add the following to your `vendorNpmFiles` array: 

``` js
'bootstrap/**/bootstrap.min.css',
'font-awesome/**/font-awesome.min.css',
'font-awesome/fonts/*',
'fuel-ui/bundles/*'
```

   3.)  `ng build`
   4.)  Add the following to your `index.html`:

``` html
<head>
  <link rel="stylesheet" href="vendor/font-awesome/css/font-awesome.min.css" />
  <link rel="stylesheet" href="vendor/bootstrap/dist/css/bootstrap.min.css" />
  <link rel="stylesheet" href="vendor/fuel-ui/bundles/fuel-ui.min.css" />
</head>

...

<!-- All your SystemJS, Angular2, Rx, zone, etc. scripts first! -->
<script src="vendor/fuel-ui/bundles/fuel-ui.min.js"></script>
```

Now you should be able to freely import from `fuel-ui/fuel-ui` and then `ng serve` your code.

I will be making an example repo to fork from for this.

EDIT: Here's the quickstart repo: https://github.com/FuelInteractive/fuel-ui-cli-quickstart/

**Comment by coryshaw1** [comment]
Created quickstart repo for Fuel-UI working with angular-cli

https://github.com/FuelInteractive/fuel-ui-cli-quickstart/
