### ISSUE TITLE
Can't seem to generate dist files fully getting an error can we include dist folder within git project?

### ISSUE THREAD

**Issue by Joebob12** [FuelInteractive/fuel-ui#69]
Hey,

I've tried installing this on two different environments and both time's I've gotten the same error. I'm not really sure what it means but it stops from creating all the files needed in the dist folder and then I can't use fuel-ui. Any help or clues into getting this working? 

Error: fuel-ui@0.2.7 postinstall: `bower install && typings install`
29678 verbose stack Exit status 1
29678 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:239:16)
29678 verbose stack     at emitTwo (events.js:106:13)
29678 verbose stack     at EventEmitter.emit (events.js:191:7)
29678 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:24:14)
29678 verbose stack     at emitTwo (events.js:106:13)
29678 verbose stack     at ChildProcess.emit (events.js:191:7)
29678 verbose stack     at maybeClose (internal/child_process.js:850:16)
29678 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
29679 verbose pkgid fuel-ui@0.2.7
29680 verbose cwd /Users/joe/ng2-play
29681 error Darwin 15.0.0
29682 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "i"
29683 error node v6.1.0
29684 error npm  v3.8.6
29685 error code ELIFECYCLE
29686 error fuel-ui@0.2.7 postinstall: `bower install && typings install`
29686 error Exit status 1
29687 error Failed at the fuel-ui@0.2.7 postinstall script 'bower install && typings install'.
29687 error Make sure you have the latest version of node.js and npm installed.
29687 error If you do, this is most likely a problem with the fuel-ui package,
29687 error not with npm itself.
29687 error Tell the author that this fails on your system:
29687 error     bower install && typings install
29687 error You can get information on how to open an issue for this project with:
29687 error     npm bugs fuel-ui
29687 error Or if that isn't available, you can get their info via:
29687 error     npm owner ls fuel-ui
29687 error There is likely additional logging output above.
29688 verbose exit [ 1, true ]

**Comment by coryshaw1** [comment]
Make sure you have bower and typings installed globally

`npm i -g bower`
`npm i -g typings`

**Comment by Joebob12** [comment]
Gah of course something easy thank you!
