### ISSUE TITLE
DataPicker has multiple issues

### ISSUE THREAD

**Issue by webmutation** [FuelInteractive/fuel-ui#73]
Hi the dateRangePicker has some strange behaviour

When gaining focus it runs an animation. on IE11 and FF the window has a scrollbar instead of being controlled by the buttons. 

http://screencast.com/t/HAElVMo80
http://screencast.com/t/O0wM12Vz

On FF the binding has issues.

**Comment by StacyGay** [comment]
The initial focus animation is intended.  I added it as an indicator to the user that months can be scrolled through.  The Angular Material Datepicker some something similar.
https://material.angularjs.org/latest/demo/datepicker

As for the binding issue, I thought I had cleaned that up.  Thanks for bringing it to my attention.

The other issues on IE and FF are valid, I'd been planing to revisit them as time permitted.
I'll be looking into it this week, I'll let you know once I've pushed some solutions.

**Comment by webmutation** [comment]
@StacyGay Sounds good. The problem is not the initial focus, its that if you leave the fuel-ui datepicker open and change tabs it will replay the animation when you switch back. If you look at the material datepicker that does not happen, it just animates once, after its open the animation is not replayed every time it regains focus.

**Comment by coryshaw1** [comment]
Closed with release v0.3.4
