### ISSUE TITLE
Update to Angular 2 RC2

### ISSUE THREAD

**Issue by coryshaw1** [FuelInteractive/fuel-ui#75]
Currently breaks Carousel and Collapse since AnimationBuilder has been removed in RC2

[Reference](https://github.com/angular/angular/issues/9259)

**Comment by henninga** [comment]
Any idea when you'll support rc2?

**Comment by coryshaw1** [comment]
We are actively working on RC2 support now. Feel free to follow along in our RC2 development branch: https://github.com/FuelInteractive/fuel-ui/tree/bugfix/RC2_Update

We still need to update Carousel to work with the new animations, and update documentation.

**Comment by coryshaw1** [comment]
Closed with release v0.3.4
